- name: "rust | Install"
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false

- name: "rust | Ensure local/bin exists"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.local/bin/"
    state: directory

#- name: "rust | download rust analyzer"
#  ansible.builtin.command:
#    cmd: "curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer"
#
#- name: "rust | download rust analyzer"
#  ansible.builtin.command:
#    cmd: "gunzip -c  > ~/.local/bin/rust-analyzer"
#
#- name: "rust | execute permissions rust analyzer"
#  ansible.builtin.file:
#    path: "/home/{{ ansible_user_id }}/.local/bin/rust-analyzer"
#    mode: u+x
#
