- name: vscode | Add repo
  yum_repository:
    name: code
    description: Visual Studio Code
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: yes
    gpgcheck: yes

- name: vscode | Install VS Code
  dnf:
    name: code
    state: latest
